version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 80:80
  node:
    build:
      dockerfile: Dockerfile.dev
      context: ./node
    ports:
      - 5000:5000
